#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["Cohub.WebApp/Cohub.WebApp.csproj", "Cohub.WebApp/"]
RUN dotnet restore "Cohub.WebApp/Cohub.WebApp.csproj"
COPY . .
WORKDIR "/src/Cohub.WebApp"
RUN dotnet build "Cohub.WebApp.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Cohub.WebApp.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Cohub.WebApp.dll"]