//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.AspNetCore.Mvc.ViewFeatures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.AspNetCore.Mvc.ViewFeatures.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or empty..
        /// </summary>
        public static string ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is of type &apos;{1}&apos;, but this method requires a value of type &apos;{2}&apos;..
        /// </summary>
        public static string ArgumentPropertyUnexpectedType {
            get {
                return ResourceManager.GetString("ArgumentPropertyUnexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partial view &apos;{0}&apos; was not found or no view engine supports the searched locations. The following locations were searched:{1}.
        /// </summary>
        public static string Common_PartialViewNotFound {
            get {
                return ResourceManager.GetString("Common_PartialViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0}.{1} could not be found..
        /// </summary>
        public static string Common_PropertyNotFound {
            get {
                return ResourceManager.GetString("Common_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        public static string Common_TriState_False {
            get {
                return ResourceManager.GetString("Common_TriState_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        public static string Common_TriState_NotSet {
            get {
                return ResourceManager.GetString("Common_TriState_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        public static string Common_TriState_True {
            get {
                return ResourceManager.GetString("Common_TriState_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} was unable to provide metadata for expression &apos;{1}&apos;..
        /// </summary>
        public static string CreateModelExpression_NullModelMetadata {
            get {
                return ResourceManager.GetString("CreateModelExpression_NullModelMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserializing TempDataDictionary.
        /// </summary>
        public static string DeserializingTempData {
            get {
                return ResourceManager.GetString("DeserializingTempData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection already contains an entry with key &apos;{0}&apos;..
        /// </summary>
        public static string Dictionary_DuplicateKey {
            get {
                return ResourceManager.GetString("Dictionary_DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewData value must not be null..
        /// </summary>
        public static string DynamicViewData_ViewDataNull {
            get {
                return ResourceManager.GetString("DynamicViewData_ViewDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression compiler was unable to evaluate the indexer expression &apos;{0}&apos; because it references the model parameter &apos;{1}&apos; which is unavailable..
        /// </summary>
        public static string ExpressionHelper_InvalidIndexerExpression {
            get {
                return ResourceManager.GetString("ExpressionHelper_InvalidIndexerExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No template &apos;{0}&apos; found..
        /// </summary>
        public static string FormatTemplateHelpers_NoTemplate {
            get {
                return ResourceManager.GetString("FormatTemplateHelpers_NoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type must implement IEnumerable {0}, {1}, {2}..
        /// </summary>
        public static string FormatTemplates_TypeMustImplementIEnumerable {
            get {
                return ResourceManager.GetString("FormatTemplates_TypeMustImplementIEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of an HTML field cannot be null or empty. Instead use methods {0}.{1} or {2}.{3} with a non-empty {4} argument value..
        /// </summary>
        public static string HtmlGenerator_FieldNameCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("HtmlGenerator_FieldNameCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no ViewData item of type &apos;{0}&apos; that has the key &apos;{1}&apos;..
        /// </summary>
        public static string HtmlHelper_MissingSelectData {
            get {
                return ResourceManager.GetString("HtmlHelper_MissingSelectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must call &apos;Contextualize&apos; method before using this HtmlHelper instance..
        /// </summary>
        public static string HtmlHelper_NotContextualized {
            get {
                return ResourceManager.GetString("HtmlHelper_NotContextualized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IModelMetadataProvider was unable to provide metadata for expression &apos;{0}&apos;..
        /// </summary>
        public static string HtmlHelper_NullModelMetadata {
            get {
                return ResourceManager.GetString("HtmlHelper_NullModelMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; must evaluate to an IEnumerable when multiple selection is allowed..
        /// </summary>
        public static string HtmlHelper_SelectExpressionNotEnumerable {
            get {
                return ResourceManager.GetString("HtmlHelper_SelectExpressionNotEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than or equal to zero..
        /// </summary>
        public static string HtmlHelper_TextAreaParameterOutOfRange {
            get {
                return ResourceManager.GetString("HtmlHelper_TextAreaParameterOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not supported. Type must be an {1} that does not have an associated {2}..
        /// </summary>
        public static string HtmlHelper_TypeNotSupported_ForGetEnumSelectList {
            get {
                return ResourceManager.GetString("HtmlHelper_TypeNotSupported_ForGetEnumSelectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ViewData item that has the key &apos;{0}&apos; is of type &apos;{1}&apos; but must be of type &apos;{2}&apos;..
        /// </summary>
        public static string HtmlHelper_WrongSelectDataType {
            get {
                return ResourceManager.GetString("HtmlHelper_WrongSelectDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property of &apos;{1}&apos; must not be null..
        /// </summary>
        public static string PropertyOfTypeCannotBeNull {
            get {
                return ResourceManager.GetString("PropertyOfTypeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No URL for remote validation could be found..
        /// </summary>
        public static string RemoteAttribute_NoUrlFound {
            get {
                return ResourceManager.GetString("RemoteAttribute_NoUrlFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid..
        /// </summary>
        public static string RemoteAttribute_RemoteValidationFailed {
            get {
                return ResourceManager.GetString("RemoteAttribute_RemoteValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializing TempDataDictionary.
        /// </summary>
        public static string SerializingTempData {
            get {
                return ResourceManager.GetString("SerializingTempData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported data type &apos;{0}&apos;..
        /// </summary>
        public static string TempData_CannotDeserializeType {
            get {
                return ResourceManager.GetString("TempData_CannotDeserializeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; cannot serialize an object of type &apos;{1}&apos;..
        /// </summary>
        public static string TempData_CannotSerializeType {
            get {
                return ResourceManager.GetString("TempData_CannotSerializeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempData serializer &apos;{0}&apos; cannot serialize property &apos;{1}.{2}&apos; of type &apos;{3}&apos;..
        /// </summary>
        public static string TempDataProperties_InvalidType {
            get {
                return ResourceManager.GetString("TempDataProperties_InvalidType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}.{1}&apos; property with {2} is invalid. A property using {2} must have a public getter and setter..
        /// </summary>
        public static string TempDataProperties_PublicGetterSetter {
            get {
                return ResourceManager.GetString("TempDataProperties_PublicGetterSetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be executed before {1} can be invoked..
        /// </summary>
        public static string TemplatedExpander_PopulateValuesMustBeInvokedFirst {
            get {
                return ResourceManager.GetString("TemplatedExpander_PopulateValuesMustBeInvokedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result of value factory cannot be null..
        /// </summary>
        public static string TemplatedExpander_ValueFactoryCannotReturnNull {
            get {
                return ResourceManager.GetString("TemplatedExpander_ValueFactoryCannotReturnNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a replacement for view expansion token &apos;{0}&apos;..
        /// </summary>
        public static string TemplatedViewLocationExpander_NoReplacementToken {
            get {
                return ResourceManager.GetString("TemplatedViewLocationExpander_NoReplacementToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate an appropriate template for type {0}..
        /// </summary>
        public static string TemplateHelpers_NoTemplate {
            get {
                return ResourceManager.GetString("TemplateHelpers_NoTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates can be used only with field access, property access, single-dimension array index, or single-parameter custom indexer expressions..
        /// </summary>
        public static string TemplateHelpers_TemplateLimitations {
            get {
                return ResourceManager.GetString("TemplateHelpers_TemplateLimitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; template was used with an object of type &apos;{1}&apos;, which does not implement &apos;{2}&apos;..
        /// </summary>
        public static string Templates_TypeMustImplementIEnumerable {
            get {
                return ResourceManager.GetString("Templates_TypeMustImplementIEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; method of type &apos;{1}&apos; cannot return a null value..
        /// </summary>
        public static string TypeMethodMustReturnNotNullValue {
            get {
                return ResourceManager.GetString("TypeMethodMustReturnNotNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must derive from &apos;{1}&apos;..
        /// </summary>
        public static string TypeMustDeriveFromType {
            get {
                return ResourceManager.GetString("TypeMustDeriveFromType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation parameter names in unobtrusive client validation rules cannot be empty. Client rule type: {0}.
        /// </summary>
        public static string UnobtrusiveJavascript_ValidationParameterCannotBeEmpty {
            get {
                return ResourceManager.GetString("UnobtrusiveJavascript_ValidationParameterCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation parameter names in unobtrusive client validation rules must start with a lowercase letter and consist of only lowercase letters or digits. Validation parameter name: {0}, client rule type: {1}.
        /// </summary>
        public static string UnobtrusiveJavascript_ValidationParameterMustBeLegal {
            get {
                return ResourceManager.GetString("UnobtrusiveJavascript_ValidationParameterMustBeLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation type names in unobtrusive client validation rules cannot be empty. Client rule type: {0}.
        /// </summary>
        public static string UnobtrusiveJavascript_ValidationTypeCannotBeEmpty {
            get {
                return ResourceManager.GetString("UnobtrusiveJavascript_ValidationTypeCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation type names in unobtrusive client validation rules must consist of only lowercase letters. Invalid name: &quot;{0}&quot;, client rule type: {1}.
        /// </summary>
        public static string UnobtrusiveJavascript_ValidationTypeMustBeLegal {
            get {
                return ResourceManager.GetString("UnobtrusiveJavascript_ValidationTypeMustBeLegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation type names in unobtrusive client validation rules must be unique. The following validation type was seen more than once: {0}.
        /// </summary>
        public static string UnobtrusiveJavascript_ValidationTypeMustBeUnique {
            get {
                return ResourceManager.GetString("UnobtrusiveJavascript_ValidationTypeMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported RenderMode &apos;{0}&apos;..
        /// </summary>
        public static string UnsupportedRenderMode {
            get {
                return ResourceManager.GetString("UnsupportedRenderMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; cannot be activated by &apos;{1}&apos; because it is either a value type, an interface, an abstract class or an open generic type..
        /// </summary>
        public static string ValueInterfaceAbstractOrOpenGenericTypesCannotBeActivated {
            get {
                return ResourceManager.GetString("ValueInterfaceAbstractOrOpenGenericTypesCannotBeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View component &apos;{0}&apos; must have exactly one public method named &apos;{1}&apos; or &apos;{2}&apos;..
        /// </summary>
        public static string ViewComponent_AmbiguousMethods {
            get {
                return ResourceManager.GetString("ViewComponent_AmbiguousMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view component name &apos;{0}&apos; matched multiple types:{1}{2}.
        /// </summary>
        public static string ViewComponent_AmbiguousTypeMatch {
            get {
                return ResourceManager.GetString("ViewComponent_AmbiguousTypeMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: &apos;{0}&apos; - Name: &apos;{1}&apos;.
        /// </summary>
        public static string ViewComponent_AmbiguousTypeMatch_Item {
            get {
                return ResourceManager.GetString("ViewComponent_AmbiguousTypeMatch_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; of view component &apos;{1}&apos; should be declared to return {2}&lt;T&gt;..
        /// </summary>
        public static string ViewComponent_AsyncMethod_ShouldReturnTask {
            get {
                return ResourceManager.GetString("ViewComponent_AsyncMethod_ShouldReturnTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A view component named &apos;{0}&apos; could not be found. A view component must be a public non-abstract class, not contain any generic parameters, and either be decorated with &apos;{1}&apos; or have a class name ending with the &apos;{2}&apos; suffix. A view component must not be decorated with &apos;{3}&apos;..
        /// </summary>
        public static string ViewComponent_CannotFindComponent {
            get {
                return ResourceManager.GetString("ViewComponent_CannotFindComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find an &apos;{0}&apos; or &apos;{1}&apos; method for the view component &apos;{2}&apos;..
        /// </summary>
        public static string ViewComponent_CannotFindMethod {
            get {
                return ResourceManager.GetString("ViewComponent_CannotFindMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View components only support returning {0}, {1} or {2}..
        /// </summary>
        public static string ViewComponent_InvalidReturnValue {
            get {
                return ResourceManager.GetString("ViewComponent_InvalidReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invoker could not be created for the view component &apos;{0}&apos;..
        /// </summary>
        public static string ViewComponent_IViewComponentFactory_ReturnedNull {
            get {
                return ResourceManager.GetString("ViewComponent_IViewComponentFactory_ReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A view component must return a non-null value..
        /// </summary>
        public static string ViewComponent_MustReturnValue {
            get {
                return ResourceManager.GetString("ViewComponent_MustReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; of view component &apos;{1}&apos; cannot return a {2}..
        /// </summary>
        public static string ViewComponent_SyncMethod_CannotReturnTask {
            get {
                return ResourceManager.GetString("ViewComponent_SyncMethod_CannotReturnTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; of view component &apos;{1}&apos; should be declared to return a value..
        /// </summary>
        public static string ViewComponent_SyncMethod_ShouldReturnValue {
            get {
                return ResourceManager.GetString("ViewComponent_SyncMethod_ShouldReturnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the &apos;{0}&apos; or &apos;{1}&apos; property must be set in order to invoke a view component..
        /// </summary>
        public static string ViewComponentResult_NameOrTypeMustBeSet {
            get {
                return ResourceManager.GetString("ViewComponentResult_NameOrTypeMustBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model item passed is null, but this ViewDataDictionary instance requires a non-null model item of type &apos;{0}&apos;..
        /// </summary>
        public static string ViewData_ModelCannotBeNull {
            get {
                return ResourceManager.GetString("ViewData_ModelCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The model item passed into the ViewDataDictionary is of type &apos;{0}&apos;, but this ViewDataDictionary instance requires a model item of type &apos;{1}&apos;..
        /// </summary>
        public static string ViewData_WrongTModelType {
            get {
                return ResourceManager.GetString("ViewData_WrongTModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The partial view &apos;{0}&apos; was not found. The following locations were searched:{1}.
        /// </summary>
        public static string ViewEngine_PartialViewNotFound {
            get {
                return ResourceManager.GetString("ViewEngine_PartialViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view &apos;{0}&apos; was not found. The following locations were searched:{1}.
        /// </summary>
        public static string ViewEngine_ViewNotFound {
            get {
                return ResourceManager.GetString("ViewEngine_ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}.{1}&apos; must not be empty. At least one &apos;{2}&apos; is required to locate a view for rendering..
        /// </summary>
        public static string ViewEnginesAreRequired {
            get {
                return ResourceManager.GetString("ViewEnginesAreRequired", resourceCulture);
            }
        }
    }
}
