select distinct TABLE_SCHEMA, TABLE_NAME --, COLUMN_NAME, COLLATION_NAME
--'ALTER TABLE '+TABLE_SCHEMA+'.'+TABLE_NAME+' ALTER COLUMN '+COLUMN_NAME+' '+DATA_TYPE+'('+CHARACTER_MAXIMUM_LENGTH+') COLLATE SQL_Latin1_General_CP1_CI_AS',
--* 
from INFORMATION_SCHEMA.COLUMNS
where COLLATION_NAME = 'SQL_Latin1_General_CP1_CI_AS'
order by TABLE_NAME
